### ISSUE TITLE
Fix tests on R16

### ISSUE THREAD

**Issue by yurrriq** [elli-lib/elli#1]
Looks like `iolist()` doesn't mean the same thing anymore.

``` erlang
-type body() :: binary() | iolist().
```

**Comment by yurrriq** [comment]
[Log](https://travis-ci.org/elli-lib/elli/jobs/157781688) for reference.

**Comment by tsloughter** [comment]
Not sure what you mean? What is the failure.

**Comment by yurrriq** [comment]
Check out the log I just linked. On R16B03-1, Dialyzer complains about something related to `elli:body()`, which is copied above.

**Comment by tsloughter** [comment]
Meh, should just ignore it or remove R16 from the tests in my opinion, hehe.

**Comment by yurrriq** [comment]
R16 build is disabled in d2d6c05, thus avoiding the issue.
