### ISSUE TITLE
ellie (or erlang ssl) not sending intermediate certs - breaks the ssl chain.

### ISSUE THREAD

**Issue by CharlesOkwuagwu** [elli-lib/elli#104]
I have setup a very simple Elli ssl server here:  https://paperlesssolutionsltd.com.ng:333

via https://www.sslshopper.com/ssl-checker.html#hostname=https://paperlesssolutionsltd.com.ng:333 I can see that the ssl chain is broken:

![image](https://user-images.githubusercontent.com/1735005/107129914-2dbcdf80-68c9-11eb-9d0a-afae54f21069.png)

Please what am i missing in my setup?

```ex
def start_link(args) do
    :elli.start_link(
      port: 333,
      certfile: Application.app_dir(@app, "priv/cert.pem"),
      keyfile: Application.app_dir(@app, "priv/cert.key"),
      ssl: true,
      callback: __MODULE__,
      callback_args: args,
      max_body_size: 1_073_741_824
    )
end
```

**Comment by CharlesOkwuagwu** [comment]
was an issue with the Erlang version. 
Upgrading to 23.2.4 solved it

https://elixirforum.com/t/making-ssl-tests-all-pass-for-phoenix-lets-encrypt/3507/30?u=charleso

**Comment by tsloughter** [comment]
Oh, good :)
