### ISSUE TITLE
Can the server handle requests for the " transfer-Encoding: chunked" header?  

### ISSUE THREAD

**Issue by SisMaker** [elli-lib/elli#109]
I looked at the project code and it seems that the HTTP parsing request code does not handle the "transfer-encoding: chunked" case, am I wrong?

**Comment by yurrriq** [comment]
It should, see also: https://github.com/elli-lib/elli/blob/2.1.2/test/elli_tests.erl#L394-L417

**Comment by SisMaker** [comment]
Ok, I'll check it out
