### ISSUE TITLE
Consider workaround for erlang:monotonic_time/0 on OTP <18

### ISSUE THREAD

**Issue by yurrriq** [elli-lib/elli#11]
If there's a need, it shouldn't be too difficult to add support for OTP <18 via preprocessor directives or similar. I have no need for it personally, but I'll leave this issue open in case someone does.

**Comment by yurrriq** [comment]
See #10 for details.

**Comment by yurrriq** [comment]
Sounds like AdRoll may have a need for this. If so, we should work it out.

**Comment by yurrriq** [comment]
@knutin, any update re: the need for support for OTP <18?

**Comment by knutin** [comment]
I think we're fine without it for these new releases.

Worst case, we can add workarounds later.

**Comment by yurrriq** [comment]
Closing for now. We can reopen should the need arise.
