### ISSUE TITLE
How to calculate request size?

### ISSUE THREAD

**Issue by deadtrickster** [elli-lib/elli#13]
Response size is trivial - Headers iolist + Body iolist, but for requests Elli uses this built-in 'event-based' parser. Currently I have no idea how to calculate request size.

**Comment by tsloughter** [comment]
Hah, I just asked this same question in slack.

**Comment by tsloughter** [comment]
Simple version in #52 just using content-length. Will need #27 for being able to track request size of anything else.

**Comment by yurrriq** [comment]
Closing in favor of instrumentation API in #27.
