### ISSUE TITLE
Request durations too large

### ISSUE THREAD

**Issue by mbucc** [elli-lib/elli#19]
I'm seeing request durations (request_end - request_start) of multiple seconds for sub-second page refreshes in browsers, but not curl.

That metric seemed like best measure of true response time (as noted in original elli sources).

What is going on?

Here's the prometheus.erl code:

```
handle_event(request_complete,
             [Req, ResponseCode, _ResponseHeaders, _ResponseBody,
              {Timings, _Sizes}],
             _Config) ->
    prometheus_counter:inc(http_requests_total,
                           [ResponseCode, rawpath(Req)]),
    Start = proplists:get_value(request_start, Timings),
    End = proplists:get_value(request_end, Timings),
    NativeDelta = End - Start,
    io:format("handle_event: ~p  ~p  ~p~n",
              [ResponseCode,
               erlang:convert_time_unit(NativeDelta, native, micro_seconds),
               rawpath(Req)]),
    prometheus_histogram:observe(response_time_in_microseconds,
                                 [rawpath(Req)], NativeDelta),
    ok;
```

the Erlang interpreter output:

```
handle_event: 200  1990847  <<"/hello/world">>
handle_event: 200  2740893  <<"/metrics">>
handle_event: 200  1239785  <<"/metrics">>
handle_event: 200  2138739  <<"/hello/world">>
```

and if I use curl instead, I get output like this:

```
handle_event: 200  1409  <<"/hello/world">>
handle_event: 200  112  <<"/hello/world">>
handle_event: 404  100  <<"/hmetrics">>
handle_event: 200  6334  <<"/metrics">>
handle_event: 200  6614  <<"/metrics">>
```

Chrome also is high:

```
handle_event: 200  183414  <<"/hello/world">>
handle_event: 404  350253  <<"/favicon.ico">>
handle_event: 200  7395448  <<"/metrics">>
handle_event: 200  3918845  <<"/metrics">>
handle_event: 200  1744633  <<"/metrics">>
```

**Comment by mbucc** [comment]
If I revert to old Elli (https://github.com/knutin/elli.git), change `{Timer, Size}` back to `Timer` and use `timer.now_diff(End, Start)`, then I get durations as I expect when using a browser:

```
handle_event: 200  4  <<"/metrics">>
handle_event: 200  3  <<"/metrics">>
handle_event: 200  0  <<"/hello/world">>
handle_event: 200  4  <<"/metrics">>
```

Is this change in behavior from 1.0.5 to 2.0.0 expected?

**Comment by yurrriq** [comment]
Also, @deadtrickster, we should add this explanation to the [overview](https://github.com/elli-lib/elli/blob/develop/doc/overview.edoc).

**Comment by deadtrickster** [comment]
Interesting.
First of, /hello/world actually sleeps for a second (I'm using it in tests I remember)

Secondly, accepted and request_start times are sometimes from the past (Not sure how to describe it -
chrome says request took 1 second): 

```
Timings: [{body_end,-576460727621513106},
          {request_end,-576460726619683576},
          {send_end,-576460726619684018},
          {headers_end,-576460727621531624},
          {user_start,-576460727621511925},
          {body_start,-576460727621513886},
          {send_start,-576460726619751786},
          {headers_start,-576460727621545677},
          {user_end,-576460726619760547},
          {accepted,-576460745295921216},
          {request_start,-576460741810312433}]
Accepted/request_end: 200  18676  [<<"hello">>,<<"world">>]
Request_start/end: 200  15190  [<<"hello">>,<<"world">>]
headeres_start/request_end: 200  1001  [<<"hello">>,<<"world">>]
```

Another try:

```
Timings: [{body_end,-576460745295829184},
          {request_end,-576460744292795662},
          {send_end,-576460744292796007},
          {headers_end,-576460745295837393},
          {user_start,-576460745295827230},
          {body_start,-576460745295829934},
          {send_start,-576460744292866437},
          {headers_start,-576460745295847688},
          {user_end,-576460744292877688},
          {accepted,-576460745295921216},
          {request_start,-576460745295912920}]
Accepted/request_end: 200  1003  [<<"hello">>,<<"world">>]
Request_start/end: 200  1003  [<<"hello">>,<<"world">>]
headeres_start/request_end: 200  1003  [<<"hello">>,<<"world">>]

```

1 second!

Can't reproduce with curl too :-)

o_O

**Comment by deadtrickster** [comment]
Keep alive?

EDIT: accepted time not erased when request finished. It dies with the handling process

**Comment by deadtrickster** [comment]
elli_http.erl handle_request

``` erlang
  t(request_start),
  Start = erlang:monotonic_time(),
  {Method, RawPath, V, B0} = get_request(S, PrevB, Opts, Callback),
  End = erlang:monotonic_time(),
  io:format("Raw: ~p~n", [erlang:convert_time_unit(End - Start, native, milli_seconds)]),
  t(headers_start),
```

when request comes from curl Raw is "always" zero. 
when first request comes from browser Raw is "always" zero
second and following requests from browser (keep-alive) - Raw is non zero

Conclusion: keep-alive related problem

Wild guess Raw correlates with time between keep-alive requests

Of course it correlates :-) keep alive implemented as rescoursive keepalive_loop,
it calls handle_request immediately after previous finished.
handle_request calls t(request_start) and hangs waiting for the next request.

**Comment by deadtrickster** [comment]
How I thought this could work

-Accept - socket accept timestamp
- Keep alive loop
  - Request Start - first byte received
    - Headers Start - HTTP request line received 
    - Headers End - HTTP headers received
  - Request End

but get_request actually collapses first_byte and request line received to the same event

So maybe all is needed is to move t(request_start) to get_request

**Comment by yurrriq** [comment]
Awesome, thanks @mbucc and @deadtrickster. I'd gladly accept a PR (with tests) to fix this, @deadtrickster. Otherwise I might be able to get to it early next week.

**Comment by mbucc** [comment]
I would like to look at the diff from 1.0.5 to see what caused the change in behavior.

**Comment by yurrriq** [comment]
The metrics (timing and now size) handling was completely rewritten. This link should work: https://github.com/knutin/elli/compare/v1.0.5...elli-lib:2.0.0

**Comment by yurrriq** [comment]
Namely #10.

**Comment by deadtrickster** [comment]
Actually I think this would be easy to fix. Right now headers_start can be used instead of request_start.

RE: PR. The idea remains the same - request_start should help to measure time-to-first-byte for the (first KA) request. For the next KA requests - time-to-second-byte (extreme example - very slow client sends one byte per second). If request is not the first, we set request_start when first byte received.

What if client's intent is to connect and wait?

**Comment by mbucc** [comment]
Looks like the order of calls changed with that #10 patch:

old:

```
-    {Method, RawPath, V, B0} = get_request(S, PrevB, Opts, Callback), t(request_start),
```

new:

```
+    t(request_start),
+    {Method, RawPath, V, B0} = get_request(S, PrevB, Opts, Callback),
```

I don't see anything else.  I'm not sure how that would cause durations get as high as seven seconds.   I think it is related to your comment above: "but get_request actually collapses first_byte and request line received to the same event".

**Comment by deadtrickster** [comment]
Ok, now when this error mentioned in blog post, we can fix it :-)
