### ISSUE TITLE
Update CHANGELOG.md

### ISSUE THREAD

**Issue by yurrriq** [elli-lib/elli#24]
- [x] [`2.0.0`](https://github.com/elli-lib/elli/releases/tag/2.0.0): [`v1.0.5...2.0.0`](https://github.com/elli-lib/elli/compare/v1.0.5...2.0.0)
- [x] [`2.0.1`](https://github.com/elli-lib/elli/releases/tag/2.0.1): [`2.0.0...2.0.1`](https://github.com/elli-lib/elli/compare/2.0.0...2.0.1)
- [x] Add CHANGELOG link to Hex metadata

**Comment by deadtrickster** [comment]
and add changelog link to hex package links...

**Comment by lpil** [comment]
Can we get one for 3.0.0? I'd like to upgrade but it unclear what has changed.

**Comment by yurrriq** [comment]
2.1.2...3.0.0 adds `scheme`, `host`, and `port` to `#req{}`

**Comment by lpil** [comment]
So we can close this?  ￼https://github.com/elli-lib/elli/issues/28 ? :)

**Comment by yurrriq** [comment]
Closing this. We can open a new one if we want to add more detail to `CHANGLOG.md`.
