### ISSUE TITLE
Changes to knutin/elli

### ISSUE THREAD

**Issue by tsloughter** [elli-lib/elli#26]
@anha0825 is merging PRs to `knutin/elli`. We need to bring them over and figure out if this is going to be the canonical or if we need to be sure to track upstream so we don't miss any changes that get merged.

**Comment by yurrriq** [comment]
:+1: I've already merged a version of https://github.com/knutin/elli/pull/101 to fit elli-lib/elli, but I agree generally.

**Comment by yurrriq** [comment]
Bump to check again.

**Comment by yurrriq** [comment]
Closing since we already have something like https://github.com/knutin/elli/pull/108 and there's nothing new.
