### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by lpil** [elli-lib/elli#39]
Hello!

Is there a recommended way of handling errors so that an application using Elli serves 500 with a suitable body whenever the handler crashes?

Thanks,
Louis

**Comment by yurrriq** [comment]
Is this behaviour insufficient?

- https://github.com/elli-lib/elli/blob/2.0.2/src/elli_example_callback.erl#L118-L121
- https://github.com/elli-lib/elli/blob/2.0.2/test/elli_tests.erl#L238-L243

**Comment by lpil** [comment]
At my company we have a specific format for error bodies.

Currently I'm catching at exceptions and thrown values in the callback and returning said body. Is this the recommended way to do this? :)

**Comment by yurrriq** [comment]
I would suggest to use `postprocess/3` something like this:

```erlang
postprocess(Req, {500, Body}, Config) ->
  custom_error(Req, [], Config);
postprocess(Req, {500, Headers, Body}, Config) ->
  custom_error(Req, Headers, Config);
postprocess(_, Res, _) ->
  Res.


custom_error(Req, Headers, Config) ->
  {500, Headers, CustomBody}.
```

**Comment by lpil** [comment]
Wonderful, thank you.

I see that `postprocess` isn't part of the `elli_handler` behaviour. I presume it goes in the same module?

**Comment by yurrriq** [comment]
Yeah! I'd love to codify an `elli_middleware` behaviour.

**Comment by lpil** [comment]
That would be great. It's quite unclear how to use the middlewear features at the moment I think.

**Comment by yurrriq** [comment]
This seems pretty related to elli-lib/elli_fileserve#7 and #3. Also note that I've spec'd out `init/2`, `preprocess/2` and `postprocess/3` as optional callbacks in `elli_handler` in 71a7c9aaf19ef2f0e782476a05c3bfb1ad5ad941.

**Comment by lpil** [comment]
That's much clearer for me, thanks :)

**Comment by yurrriq** [comment]
Great! I’ll publish a new release in the next few days.

**Comment by yurrriq** [comment]
https://hex.pm/packages/elli/2.1.2

Feel free to re-open if need be, but I'm closing this for now.
