### ISSUE TITLE
Handling exceptions via middleware

### ISSUE THREAD

**Issue by lpil** [elli-lib/elli#50]
Hello!

I'd like to create an Elli middleware for reporting exceptions that we can use in all our services. When added to the middleware stack it would catch any errors thrown by later middleware (or receive a report of these errors) and send them to our error aggregation service.

Is it possible to do this with the current Elli middleware system? I've been unable to find a way to do this and have instead wrapped the middleware module to add this functionality.

Thanks,
Louis

**Comment by yurrriq** [comment]
Does [`handle_event/3`](https://github.com/elli-lib/elli/blob/3.0.0/src/elli_handler.erl#L39-L42) work for you?

```erlang
-spec handle_event(Event, Args, Config) -> ok when
      Event  :: elli:event(),
      Args   :: elli_handler:callback_args(),
      Config :: [tuple()].
handle_event(request_throw, [_Request, _Exception, _Stacktrace], _) -> ok;
handle_event(request_error, [_Request, _Exception, _Stacktrace], _) -> ok;
handle_event(request_exit, [_Request, _Exception, _Stacktrace], _)  -> ok;
handle_event(_Event, _Args, _Config)                                -> ok.
```

**Comment by lpil** [comment]
Wonderful, thank you!

**Comment by yurrriq** [comment]
You’re welcome! Glad I could help.
