### ISSUE TITLE
Fully drop support for OTP <18

### ISSUE THREAD

**Issue by yurrriq** [elli-lib/elli#56]
We "officially" support 18+, so let's drop any lingering obviated conditional logic,
e.g. the `-ifdef('16.0')` in #55.

**Comment by galdor** [comment]
The title says to drop <=18, but the body says 18+ is supported. Which one is right ? I'm not sure there is any point in supporting 18.x, but who knows :)

**Comment by yurrriq** [comment]
Good question. I can't remember. I think maybe I meant <18.

**Comment by galdor** [comment]
In any case I believe this issue could be closed now.
