### ISSUE TITLE
Cut new release

### ISSUE THREAD

**Issue by yurrriq** [elli-lib/elli#6]
The elli-lib version has several improvements over the currently published version (1.0.5), namely wrt type naming collisions. I've merged `develop` into `master` and think it's good to go. The open issues either pertain to documentation or can wait.

@knutin, would you prefer I open a PR to knutin/elli, or should we just publish from here? Also, by _we_, I mean you, since you're the owner of the Hex package. :smile:

**Comment by tsloughter** [comment]
You may want to email him :)

Also note that he could add both or one of us to the hex package ownership if he was comfortable with that with `rebar3 hex owner add elli t@crashfast.com`.

**Comment by deadtrickster** [comment]
Can you publish prefixed package in the meantime?

**Comment by yurrriq** [comment]
Sounds like @knutin will add @tsloughter and me as owners soon. Then we can cut and publish a release.

We'll want to be sure the version reflects the breaking changes. Maybe 1.2.5 isn't dramatic enough.

**Comment by tsloughter** [comment]
What is the breaking change? If it is not backwards compatible it'll have to go to 2.0.0.

**Comment by yurrriq** [comment]
https://github.com/elli-lib/elli/compare/b617611a5a552c264b4a69a0d44d998621d3ad18...6d96cd87302f2542b2cc9fb40e4a1292955f9fa7

**Comment by tsloughter** [comment]
So the metrics callbacks changed or something? In that case then 2.0.0, if it is just removal of older OTP support than 1.2.0 is fine.

**Comment by yurrriq** [comment]
Yeah, instead of just `Timings` it now returns `{Timings,Sizes}`. I've bumped to 2.0.0 and cleaned up the docs. I think we should be all set for 2.0.0.

**Comment by yurrriq** [comment]
We may want to come up with a solution for #13 first.

**Comment by deadtrickster** [comment]
What about this one: https://github.com/elli-lib/elli/pull/14. Travis build fails but locally it's green ¯_(ツ)_/¯

**Comment by yurrriq** [comment]
Haven't had a chance to look at it, that'd be good too.

**Comment by yurrriq** [comment]
@tsloughter and I have Hex rights now. Is there anything else we wanna do before cutting 2.0.0?

**Comment by yurrriq** [comment]
Bump. I think we're good to go. What do y'all think?

**Comment by deadtrickster** [comment]
Let's do this 👍

**Comment by yurrriq** [comment]
Published [2.0.0](https://hex.pm/packages/elli/2.0.0). Please test and let me know how it goes.
