### ISSUE TITLE
Unable to run pre hooks for 'compile', command 'erl_vsn' not found. in 3.1.0

### ISSUE THREAD

**Issue by johnhamelink** [elli-lib/elli#60]
Hi guys,

I'm trying to upgrade from 3.0 to 3.1, but I'm getting the following error on both my dev machine and in CI:

```
===> Fetching rebar_erl_vsn ({pkg,<<"rebar_erl_vsn">>,<<"0.1.7">>})
===> Downloaded package, caching at /home/john/.cache/rebar3/hex/default/packages/rebar_erl_vsn-0.1.7.tar
===> Compiling rebar_erl_vsn
===> Compiling elli
===> Unable to run pre hooks for 'compile', command 'erl_vsn' not found.
** (Mix) Could not compile dependency :elli, "/home/john/.asdf/installs/elixir/1.6.3/.mix/rebar3 bare compile --paths "/home/john/code/hc/dylan/_build/test/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile elli", update it with "mix deps.update elli" or clean it with "mix deps.clean elli"
```

It seems that since 3.0, `rebar_erl_vsn` was added to `rebar.config`, could this be the source of the issue?

I'm running Erlang 20.3.6 and Elixir 1.6.3.

**Comment by lpil** [comment]
Hi friends, any update here? It'd be great to use the latest Elli

**Comment by yurrriq** [comment]
Looks like maybe a Mix issue to me. As a workaround could override the elli hooks in your `rebar.config`.

**Comment by ghost** [comment]
Similar issue [here](https://github.com/erlang/rebar3/issues/1804) you might want to follow. B

**Comment by lpil** [comment]
The above issue is closed, does that mean this is fixed?

**Comment by ghost** [comment]
@lpil I believe so, but you'll need to ensure you're running rebar3 v 3.6.0 or higher.
* https://github.com/erlang/rebar3/releases/tag/3.6.0
* https://github.com/erlang/rebar3/pull/1810

**Comment by lpil** [comment]
It works! Shall we close this?

**Comment by ghost** [comment]
@johnhamelink ?

**Comment by lpil** [comment]
FWIW, John and I work together at Honeycomb TV, we've resolved the issue in the projects in question :)

**Comment by johnhamelink** [comment]
Thanks guys :)
