### ISSUE TITLE
apply check_max_size logic to headers as well

### ISSUE THREAD

**Issue by ghost** [elli-lib/elli#65]
Right now it's possible to "load" the socket with large headers, so I don't think there are any checks for this scenario (other than headers count < 100).

**Comment by ghost** [comment]
Example of a failing test (in elixir)

```elixir
  test "fails on large headers" do
    cookie = "bar=" <> String.duplicate("a", 10_000_000) # 10 MB binary
    response = request(:get, "/headers", [{"cookie", cookie}]) # GET request with cookie header bar=aaaaa...
    assert match?({400, _, _}, response) or match?({:error, :closed}, response) # elli returns 200, consumes all headers
    assert {200, _, _} = request(:get, "/headers", [{"foo", "bar"}, {"baz", "bat"}])
  end
```

**Comment by ghost** [comment]
Possibly applies to the request line (`get_request`) as well.

```http
GET /aaaaaaa[... and 10MB more of aaaaa] HTTP/1.1
```

**Comment by yurrriq** [comment]
Looks like a bug to me. Thanks for pointing it out. PRs are most welcome!

**Comment by ghost** [comment]
> Thanks for pointing it out. PRs are most welcome!

Great! I'll try to make one today.
