### ISSUE TITLE
Consider not using X-Forwarded-For as a primary source of the peer address

### ISSUE THREAD

**Issue by ldmberman** [elli-lib/elli#68]
`elli_request:peer/1` [uses X-Forwarded-For](https://github.com/elli-lib/elli/blob/develop/src/elli_request.erl#L69) as the primary source of the request origin.

This is concerning because the header can not be trusted so applications using `elli` are not able to rely on `elli_request:peer/1` when IP addresses are used in scoring systems and blacklists.

At the very least, it would be helplful to have a separate function that uses `elli_tcp:peername(Socket)` to exclude the peer address.

Ideally though, `X-Forwarded-For` should not be used in `peer/1`.

Thank you!

**Comment by yurrriq** [comment]
Thanks for the feedback! Pull requests are most welcome, and we'll do our best to review in a timely manner.

**Comment by tsloughter** [comment]
Resolved by #75
