### ISSUE TITLE
Replace os:timestamp with monotnic time.

### ISSUE THREAD

**Issue by deadtrickster** [elli-lib/elli#7]
https://github.com/elli-lib/elli/blob/develop/src/elli_http.erl#L583 here. 
timestamp is highly unreliable for measuring duration (i.e. time warps).

**Comment by yurrriq** [comment]
Good call. I'd be happy to accept a PR. Can we artificially create a time warp in a test too?

**Comment by deadtrickster** [comment]
The most obvious is to change OS time which requires permissions elevation. Why would you want to test this? No trust for OTP team :-)?

**Comment by yurrriq** [comment]
Heh, fair point. We should use monotonic time though for sure.

**Comment by deadtrickster** [comment]
how about backward incompatibility? should we even care about this? looks like upstream is 'stalled'?

**Comment by yurrriq** [comment]
No, I don't think we should care. We might take care to amend any other middleware that use this timings, e.g. `elli_prometheus`, but in general this fork doesn't aim to be entirely backward compatible. I still need to lay out a proper plan and email @knutin...
