### ISSUE TITLE
SSL_accept deprecated since OTP 21

### ISSUE THREAD

**Issue by jmmontenot** [elli-lib/elli#76]
Since OTP 21,
ssl:ssl_accept/2: deprecated; use ssl:handshake/2 instead

a little bit of explanation about this change can be found [here](https://blog.voltone.net/post/19)

it's only a warning during compilation, but it's you use warning_as_error for production mode, it might be a problem;

handshake method not exist before OTP 21, it's not very easy to switch to this version. 
do you have roadmap to take all compatibility with OTP 21 ?

**Comment by yurrriq** [comment]
Thanks for pointing this out! For now we support back to 18.0, but I'm not sure we need to go that far anymore. Thoughts, @tsloughter?

**Comment by tsloughter** [comment]
Huh, could have swore we already fixed this. I can send a PR later today to wrap the usage i a macro to use one or the other depending on the version of OTP.

**Comment by yurrriq** [comment]
Me too. Didn't this solve it? https://github.com/elli-lib/elli/pull/61

**Comment by tsloughter** [comment]
Yea, should have. So either the regex doesn't work right or maybe @jmmontenot you are on an old version of elli?

Though I would change it to use just `-ifdef(OTP_RELEASE)` for otp21+ to be simpler but not important.

**Comment by jmmontenot** [comment]
you are right, I had not read the code, -ifdef(post20) is present to switch between ssl:handshake or ssl:ssl_accept (i use Elli 3.2.0). 

by adding {d, post20) in rebar compilation options, it's works. 

I agree with @tsloughter, it would be easier with -ifdef(OTP_RELEASE) / -if(?OTP_RELEASE >= 21). 
maybe for a next enhancement.

thanks for your support.
