### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [elli-lib/elli#86]
Hi. Do you suppose we'll have a release soon? `master` seems to have fallen a bit behind develop, but in the meanwhile 3.1.0 and 3.2.0 have been released and post-3.2.0 code has been added to develop. Thanks.

**Comment by tsloughter** [comment]
Sure, I think so.

As for master... ugh, I dislike that `master` is not the default branch :). I'd like to change this project to simply use master as the default branch and get rid of that issue.

@yurrriq are you ok with that?

**Comment by paulo-ferraz-oliveira** [comment]
:-) I tend to use `master` and `develop` in development teams (private projects), but not public projects, since this brings extra overhead that's usually not that useful. In any case, we also use git-flow and the develop/master combo seems to work just fine.

**Comment by yurrriq** [comment]
I'm fine either way.

**Comment by paulo-ferraz-oliveira** [comment]
Hi, @tsloughter. I'm going to create a new PR so that nothing from `develop` gets lost in `master` and then you can release when time allows for it.

**Edit**: I've opened #89 so that a release may occur. Closing this one!

**Comment by paulo-ferraz-oliveira** [comment]
I'm reopening this as a way to re-request the release, since I closed #89 as discussed previously.

**Comment by tsloughter** [comment]
Sorry about that, done this morning. 3.3.0 is published.

**Comment by tsloughter** [comment]
Default branch has been changed to `main`. I deleted the `master` branch since that'd jus tbe confusing and it was 51 commits behind `develop`. I think we should delete `develop` soon to also not cause confusion.

**Comment by paulo-ferraz-oliveira** [comment]
> Sorry about that, done this morning. 3.3.0 is published.

Hm... :D did you push it? https://github.com/elli-lib/elli/tags states `3.2.0` as latest.

**Comment by paulo-ferraz-oliveira** [comment]
> I think we should delete `develop` soon to also not cause confusion.

I agree. 👍

**Comment by tsloughter** [comment]
Forgot the tag, will push that in a minute.

**Comment by paulo-ferraz-oliveira** [comment]
You didn't, did you? :D

**Comment by tsloughter** [comment]
pushed

**Comment by paulo-ferraz-oliveira** [comment]
I confirm :D thanks for this.
