### ISSUE TITLE
Elli throws an exception when returning unexpected HTTP status codes

### ISSUE THREAD

**Issue by jeffgrunewald** [elli-lib/elli#95]
It appears that when attempting to generate an HTTP status code binary description, Elli is unable to handle any codes that are not included in the list of handled function heads in `elli_http.erl` or a binary.

When receiving and attempting to handle non-standard or uncommon HTTP status codes, the handler crashes.

Since `elli.erl` declares a response type to be any integer between 100..999 inclusive, it should have a valid fall-through behavior for handling integer status codes that are not expected by that prepared list of `status/1` function heads [here](https://github.com/elli-lib/elli/blob/3fa6faa816a2b92cd64149744d8f7dd43bfe1565/src/elli_http.erl#L846)

**Comment by yurrriq** [comment]
Thanks for the report and PR. Merged #96.
